version: '3.8'

services:
  kelburg_frontend:
    image: kelburg_frontend:latest
    ports:
      - "13000:13000"
    environment:
      - ASPNETCORE_URLS=http://+:13000
  db_new:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB_FILE: /run/secrets/database_new
      POSTGRES_USER_FILE: /run/secrets/dbuser_new
      POSTGRES_PASSWORD_FILE: /run/secrets/dbpassword_new
    secrets:
      - database_new
      - dbuser_new
      - dbpassword_new
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: 
      ["postgres", "-c", "wal_level=logical"]

  api:
    image: kelburg_api:latest
    environment:
      DefaultConnection: /run/secrets/DefaultConnection
      JwtSettings__Key: /run/secrets/Key
      JwtSettings__Issuer: /run/secrets/Issuer
      JwtSettings__Audience: /run/secrets/Audience
      SecretApiKey: /run/secrets/SecretApiKey
      CancelUrl: /run/secrets/SecretApiKey
      SuccessUrl: /run/secrets/SecretApiKey
      
    secrets:
    - DefaultConnection
    - Key
    - Issuer
    - Audience
    - SecretApiKey
    - CancelUrl
    - SuccessUrl
    depends_on:
      - db
    ports:
      - "8080:8080"
secrets:
    database_new:
      external: true
    dbuser_new:
      external: true
    dbpassword_new:
      external: true
    DefaultConnection:
      external: true
    Key:
      external: true
    Issuer:
      external: true
    Audience:
      external: true
    SecretApiKey:
      external: true
    CancelUrl:
      external: true
    SuccessUrl:
      external: true

volumes:
  pg_data: