version: '3.8'

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: /run/secrets/database
      POSTGRES_USER: /run/secrets/dbuser
      POSTGRES_PASSWORD: /run/secrets/dbpassword
    secrets:
      - database
      - dbuser
      - dbpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: kelburg_api:latest
    environment:
      DefaultConnection: /run/secrets/DefaultConnection
      JwtSettings__Key: /run/secrets/Key
      JwtSettings__Issuer: /run/secrets/Issuer
      JwtSettings__Audience: /run/secrets/Audience
    secrets:
      - DefaultConnection
      - Key
      - Issuer
      - Audience
    depends_on:
      - database
    ports:
      - "8080:8080"
secrets:
  database:
    external: true
  dbuser:
    external: true
  dbpassword:
    external: true
  DefaultConnection:
    external: true
  Key:
    external: true
  Issuer:
    external: true
  Audience:
    external: true

volumes:
  pg_data: